using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Major Code Smell", "S6960:Controllers should not have mixed responsibilities", Justification = "Reviewed and dismissed as false-positive on SonarCloud", Scope = "type", Target = "~T:Lighthouse.Backend.API.PortfolioController")]
[assembly: SuppressMessage("Major Code Smell", "S6960:Controllers should not have mixed responsibilities", Justification = "Reviewed and dismissed as false-positive on SonarCloud", Scope = "type", Target = "~T:Lighthouse.Backend.API.SystemInfoController")]
[assembly: SuppressMessage("Major Code Smell", "S6960:Controllers should not have mixed responsibilities", Justification = "Reviewed and dismissed as false-positive on SonarCloud", Scope = "type", Target = "~T:Lighthouse.Backend.API.WorkTrackingSystemConnectionsController")]
[assembly: SuppressMessage("Minor Code Smell", "S1118:Utility classes should not have public constructors", Justification = "Reviewed and dismissed on SonarCloud; Program is the ASP.NET Core entry point", Scope = "type", Target = "~T:Lighthouse.Backend.Program")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "Reviewed and dismissed on SonarCloud; the Linear API endpoint is a fixed public URL", Scope = "member", Target = "~F:Lighthouse.Backend.Services.Implementation.WorkTrackingConnectors.Linear.LinearWorkTrackingOptionNames.ApiUrl")]
[assembly: SuppressMessage("Security Hotspot", "S5122:Restrict this CORS policy to trusted origins", Justification = "AllowAnyOrigin applies only when authentication is disabled and no origins are configured; a self-hosted, unauthenticated instance intentionally serves any origin", Scope = "type", Target = "~T:Lighthouse.Backend.Program")]
[assembly: SuppressMessage("Security Hotspot", "S5332:Using http protocol is insecure. Use https instead", Justification = "String replacement only rewrites the startup console banner to display localhost URLs; no network traffic uses these strings", Scope = "type", Target = "~T:Lighthouse.Backend.Program")]
[assembly: SuppressMessage("Security Hotspot", "S2245:Using pseudorandom number generators (PRNGs) is security-sensitive", Justification = "Used solely for Monte Carlo forecast simulation, not for any security-sensitive value; System.Random is the correct choice", Scope = "member", Target = "~M:Lighthouse.Backend.Services.Implementation.RandomNumberService.GetRandomNumber(System.Int32)~System.Int32")]
[assembly: SuppressMessage("Security Hotspot", "S4036:Make sure the \"PATH\" used to find this command includes only what you intend", Justification = "PostgreSQL client tools (pg_dump/pg_restore/psql) are resolved via PATH deliberately for cross-platform and container portability", Scope = "type", Target = "~T:Lighthouse.Backend.Services.Implementation.DatabaseManagement.PostgresDatabaseManagementProvider")]
[assembly: SuppressMessage("Security Hotspot", "S4036:Make sure the \"PATH\" used to find this command includes only what you intend", Justification = "chmod is resolved via PATH deliberately for cross-platform and container portability", Scope = "type", Target = "~T:Lighthouse.Backend.Services.Implementation.LighthouseReleaseService")]
[assembly: SuppressMessage("Security Hotspot", "S5693:Make sure the content length limit is safe here", Justification = "The database restore upload endpoint intentionally allows a 512 MB backup file via an explicit RequestSizeLimit", Scope = "type", Target = "~T:Lighthouse.Backend.API.DatabaseManagementController")]
