# Required metadata
sonar.projectKey=LetPeopleWork_Lighthouse_Frontend
sonar.projectName=Lighthouse.Frontend
sonar.organization=letpeoplework
sonar.sources=src
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/*.test.ts, **/*.test.tsx, **/__tests__/**, ../Lighthouse.Backend/**, ../Lighthouse.EndToEndTests/**

sonar.testExecutionReportPaths=sonar-report.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Language specific options
sonar.language=typescript
sonar.typescript.file.suffixes=.ts,.tsx

sonar.typescript.tsconfigPath=tsconfig.app.json

sonar.javascript.node.maxspace=8192


sonar.verbose=true
sonar.log.level=DEBUG