source 'https://rubygems.org'

gem "jekyll", "~> 4.4.1" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

gem "just-the-docs", "0.12.0" # pinned to the current release
# gem "just-the-docs"        # always download the latest release

gem "google-protobuf", "~> 4.36", ">= 4.36.2"

gem "csv"

gem "logger"
gem "base64"
gem "bigdecimal"
gem "mutex_m"
gem "erb"