name: Verify SonarCloud Quality Gates

on:
  workflow_call:
    inputs:
      frontend-ran:
        type: boolean
        required: true
      backend-ran:
        type: boolean
        required: true

jobs:
  sonar-gates:
    if: inputs.frontend-ran || inputs.backend-ran
    runs-on: ubuntu-latest
    steps:
      - name: Download Frontend Sonar report
        if: inputs.frontend-ran
        uses: actions/download-artifact@v8
        with:
          name: sonar-report-frontend
          path: ./Lighthouse.Frontend/.scannerwork/

      - name: Wait for Frontend Quality Gate
        if: inputs.frontend-ran
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        with:
          scanMetadataReportFile: ./Lighthouse.Frontend/.scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Download Backend Sonar report
        if: inputs.backend-ran
        uses: actions/download-artifact@v8
        with:
          name: sonar-report-backend
          path: .sonarqube/out/.sonar/

      - name: Wait for Backend Quality Gate
        if: inputs.backend-ran
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        with:
          scanMetadataReportFile: .sonarqube/out/.sonar/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Checkout
        if: inputs.frontend-ran
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: '0'

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320
        with:
          version: 10
          run_install: false

      - name: Use Node.js
        if: inputs.frontend-ran
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: '24'
          cache: 'pnpm'
          cache-dependency-path: './Lighthouse.Frontend/pnpm-lock.yaml'
      
      - name: Audit Frontend Dependencies
        if: inputs.frontend-ran && github.ref == 'refs/heads/main'
        working-directory: ./Lighthouse.Frontend
        run: pnpm audit --audit-level=low