name: Build Codesign Runner Image

on:
  push:
    branches: [ "main" ]
    paths:
      - "tools/codesign/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "tools/codesign/**"
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Codesign Runner Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          use: true

      - name: Build Docker image
        if: github.event_name == 'pull_request'
        run: |
          docker build \
            --file tools/codesign/Dockerfile \
            --tag lighthouse-codesign-runner:pr-test \
            tools/codesign

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          
          docker buildx build \
            --platform linux/amd64 \
            --file tools/codesign/Dockerfile \
            --tag ghcr.io/${REPO_NAME}-codesign-runner:latest \
            --tag ghcr.io/${REPO_NAME}-codesign-runner:${{ github.sha }} \
            --push \
            tools/codesign
