name: Nightly Backend CI

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  backend:
    uses: ./.github/workflows/ci_backend.yml
    with:
      backend: "true"
      run_sonar: true
      connector_shared: "true"
      jira_connector: "false"
      ado_connector: "false"
      linear_connector: "false"
      github_connector: "false"
    secrets: inherit