// <auto-generated />
using System;
using CMFTAspNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMFTAspNet.Migrations
{
    [DbContext(typeof(CMFTAspNetContext))]
    partial class CMFTAspNetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("CMFTAspNet.Models.Teams.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalRelatedFields")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaPaths")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FeatureWIP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IgnoredTags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawThroughput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ThroughputHistory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkItemTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkTrackingSystem")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("CMFTAspNet.WorkTracking.WorkTrackingSystemOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("WorkTrackingSystemOption");
                });

            modelBuilder.Entity("CMFTAspNet.WorkTracking.WorkTrackingSystemOption", b =>
                {
                    b.HasOne("CMFTAspNet.Models.Teams.Team", null)
                        .WithMany("WorkTrackingSystemOptions")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("CMFTAspNet.Models.Teams.Team", b =>
                {
                    b.Navigation("WorkTrackingSystemOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
